### PR TITLE
Adding end-index to dictionary representation of an Entity

### PR DESCRIPTION
**Pull request by ValentinCalomme**
The feature request implemented by this pull request is described in #32

In short, this minimal pull request allows the JSONL adapter to also output the end-index of a slot, making it much easier to infer the span of an entity. 

PS: this is my first PR on this repo, am not sure whether I am trying to get my changes to be pulled into the right branch

### CODE REVIEW

**Comment by SimGus** [comment]
This is the right branch to merge into. I use the following logic:
- `master` contains the code of the latest release
- `dev` contains the latest stable code (possibly with added features and bug fixed since the last release)
I'll add this information to the `CONTRIBUTE` file.

The code seems alright to me :)
That being said, the code will use a little more memory than it used to. If memory consumption becomes a critical criterion, I will move the calculation of the end index to the JSONL adapter itself.

I will merge this, update the changelog and add you to the list of contributors! Thanks again!

**Comment by ValentinCalomme** [comment]
Great! And makes sense. Indeed, this could potentially be a parameter during generation if memory becomes scarce.

It was only changing a single line of code but would be happy to contribute in other ways. Do you have a list of features you'd like to add at some point? Could be things like docstrings, type hints, documentation, more tests etc.

If yes, then I'll have a look and see what I can contribute to!

**Comment by SimGus** [comment]
Actually, I just checked and I'm wrong about the memory consumption: `Entity.as_dict()` is only called in the JSONL adapter at the moment, so this change has no disadvantage.

I have a list of features I am thinking of adding in [TODO.md](https://github.com/SimGus/Chatette/blob/master/TODOs.md), but I don't think it's very clear. I'll see if I can use some of the new project management features of GitHub to make a clearer list.
You can take a look at this list and hit me up if you find something that you'd be interested in doing, or if you need clarifications :)

Btw, I'm not using type hints because I want to support Python 2.7 until its EOL, and it doesn't support type hints (not that I know of at least).

**Comment by ValentinCalomme** [comment]
Indeed, 2.7 doesn't, there is something like type-comments, but it's different than what 3+ supports

Sounds good!

**Pull request merged**
